version: '3.8'
services:
  app:
    build: .
    container_name: node_app
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  nginx:
    image: nginx
    container_name: nginx_node
    ports:
      - "80:80"
    volumes:
      - ../nginx.conf:/etc/nginx/nginx.conf:ro
