version: '3.8'

services:
  app:
    build: .
    container_name: springboot_app
    ports:
      - "5000:5000"
    networks:
      - app-network

  nginx:
    image: nginx
    container_name: nginx_spring
    ports:
      - "80:80"
    volumes:
      - ../nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
